"@generated by translate_pnpm_lock.bzl from //:pnpm-lock.json"

load("@aspect_rules_js//js:npm_import.bzl", "npm_import")

def npm_repositories():
    npm_import(
        name = "npm__acorn_8.7.0",
        integrity = "sha512-V/LGr1APy+PXIwKebEWrkZPwoeoF+w1jiOBUmuxuiUIaOHtob8Qc9BTrYo7VuI5fR8tqsy+buA2WFooR5olqvQ==",
        link_package_guard = "",
        package = "acorn",
        version = "8.7.0",
        indirect = True,
    )

    npm_import(
        name = "npm__buffer-from_1.1.2",
        integrity = "sha512-E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==",
        link_package_guard = "",
        package = "buffer-from",
        version = "1.1.2",
        indirect = True,
    )

    npm_import(
        name = "npm__commander_2.20.3",
        integrity = "sha512-GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==",
        link_package_guard = "",
        package = "commander",
        version = "2.20.3",
        indirect = True,
    )

    npm_import(
        name = "npm__source-map-support_0.5.21",
        integrity = "sha512-uBHU3L3czsIyYXKX88fdrGovxdSCoTGDRZ6SYXtSRxLZUzHg5P/66Ht6uoUlHu9EZod+inXhKo3qQgwXUT/y1w==",
        link_package_guard = "",
        package = "source-map-support",
        version = "0.5.21",
        deps = {
            "buffer-from": "1.1.2",
            "source-map": "0.6.1",
        },
        indirect = True,
    )

    npm_import(
        name = "npm__source-map_0.6.1",
        integrity = "sha512-UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==",
        link_package_guard = "",
        package = "source-map",
        version = "0.6.1",
        indirect = True,
    )

    npm_import(
        name = "npm__source-map_0.7.3",
        integrity = "sha512-CkCj6giN3S+n9qrYiBTX5gystlENnRW5jZeNLHpe6aue+SrHcG5VYwujhW9s4dY31mEGsxBDrHR6oI69fTXsaQ==",
        link_package_guard = "",
        package = "source-map",
        version = "0.7.3",
        indirect = True,
    )

    npm_import(
        name = "npm__terser_5.12.1",
        integrity = "sha512-NXbs+7nisos5E+yXwAD+y7zrcTkMqb0dEJxIGtSKPdCBzopf7ni4odPul2aechpV7EXNvOudYOX2bb5tln1jbQ==",
        link_package_guard = "",
        package = "terser",
        version = "5.12.1",
        deps = {
            "acorn": "8.7.0",
            "commander": "2.20.3",
            "source-map": "0.7.3",
            "source-map-support": "0.5.21",
        },
    )
