queue: oss-gcp-default
bazel:
  flags:
    - --config=rbe
workspaces:
  .:
    tasks:
      - test:
          targets:
            - //...
      - configure:
          bazel:
            flags: [] # TODO: Aspect CLI does not support --config for configure cmd
  e2e/smoke:
    icon: bazel
    tasks:
      - test:
          queue: oss-gcp-small
      - format:
          without: true
      - gazelle:
          without: true
      - configure:
          without: true
      - buildifier:
          without: true
      - delivery:
          without: true
tasks:
  - test:
  - format:
      queue: oss-gcp-small
  - gazelle:
      queue: oss-gcp-small
  - configure:
      queue: oss-gcp-small
  - buildifier:
      queue: oss-gcp-small
  - delivery:
      auto_deliver: true
      rules:
        - deliverable: 'attr("tags", "\bdeliverable\b", //...)'
          condition:
            branches:
              - main
        - deliverable:
            - //docs:docs_delivery
          condition:
            only_on_change: false
            branches:
              - main
  - warming:
      queue: oss-gcp-warming
notifications:
  github: {}
