# See https://docs.aspect.build/workflows/configuration
workspaces:
  .:
    tasks:
      - test:
  e2e/smoke:
    tasks:
      - test:
          queue: aspect-medium
      - format:
          without: true
      - configure:
          without: true
      - buildifier:
          without: true
bazel:
  flags:
    - --config=ci
tasks:
  - test:
  - format:
      queue: aspect-medium
  - configure:
      queue: aspect-medium
      flags:
  - buildifier:
      queue: aspect-medium
  - finalization:
      queue: aspect-small
notifications:
  github: {}
