"""npm repositories for tmp.XppBOrVg
@generated by translate_package_lock.bzl from
//:package-lock.json
"""

load("@aspect_rules_js//js:npm_import.bzl", "npm_import")

def npm_repositories():
    "Define external repositories to fetch each tarball individually from npm on-demand."

    npm_import(
        name = "npm_acorn-8.7.0",
        integrity = "sha512-V/LGr1APy+PXIwKebEWrkZPwoeoF+w1jiOBUmuxuiUIaOHtob8Qc9BTrYo7VuI5fR8tqsy+buA2WFooR5olqvQ==",
        package = "acorn",
        version = "8.7.0",
        deps = [],
    )

    npm_import(
        name = "npm_buffer-from-1.1.2",
        integrity = "sha512-E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==",
        package = "buffer-from",
        version = "1.1.2",
        deps = [],
    )

    npm_import(
        name = "npm_commander-2.20.3",
        integrity = "sha512-GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==",
        package = "commander",
        version = "2.20.3",
        deps = [],
    )

    npm_import(
        name = "npm_source-map-0.7.3",
        integrity = "sha512-CkCj6giN3S+n9qrYiBTX5gystlENnRW5jZeNLHpe6aue+SrHcG5VYwujhW9s4dY31mEGsxBDrHR6oI69fTXsaQ==",
        package = "source-map",
        version = "0.7.3",
        deps = [],
    )

    npm_import(
        name = "npm_source-map-support-0.5.21",
        integrity = "sha512-uBHU3L3czsIyYXKX88fdrGovxdSCoTGDRZ6SYXtSRxLZUzHg5P/66Ht6uoUlHu9EZod+inXhKo3qQgwXUT/y1w==",
        package = "source-map-support",
        version = "0.5.21",
        deps = ["@npm_buffer-from-1.1.2", "@npm_source-map-0.7.3"],
    )

    npm_import(
        name = "npm_terser-5.12.1",
        integrity = "sha512-NXbs+7nisos5E+yXwAD+y7zrcTkMqb0dEJxIGtSKPdCBzopf7ni4odPul2aechpV7EXNvOudYOX2bb5tln1jbQ==",
        package = "terser",
        version = "5.12.1",
        deps = ["@npm_acorn-8.7.0", "@npm_commander-2.20.3", "@npm_source-map-0.7.3", "@npm_source-map-support-0.5.21"],
    )
