"@generated by @aspect_rules_js//js/private:translate_pnpm_lock.bzl from pnpm lock file @//:pnpm-lock.yaml"

# buildifier: disable=bzl-visibility
load("@aspect_rules_js//js/private:pnpm_utils.bzl", _pnpm_utils = "pnpm_utils")
load("@bazel_skylib//lib:paths.bzl", _paths = "paths")
load("@npm__acorn__8.7.1__links//:link_js_package.bzl", link_0 = "link_js_package")
load("@npm__buffer-from__1.1.2__links//:link_js_package.bzl", link_1 = "link_js_package")
load("@npm__commander__2.20.3__links//:link_js_package.bzl", link_2 = "link_js_package")
load("@npm__lodash.sortby__4.7.0__links//:link_js_package.bzl", link_3 = "link_js_package")
load("@npm__punycode__2.1.1__links//:link_js_package.bzl", link_4 = "link_js_package")
load("@npm__source-map-support__0.5.21__links//:link_js_package.bzl", link_5 = "link_js_package")
load("@npm__source-map__0.6.1__links//:link_js_package.bzl", link_6 = "link_js_package")
load("@npm__source-map__0.8.0-beta.0__links//:link_js_package.bzl", link_7 = "link_js_package")
load("@npm__terser__5.13.0__links//:link_js_package.bzl", link_8 = "link_js_package")
load("@npm__tr46__1.0.1__links//:link_js_package.bzl", link_9 = "link_js_package")
load("@npm__webidl-conversions__4.0.2__links//:link_js_package.bzl", link_10 = "link_js_package")
load("@npm__whatwg-url__7.1.0__links//:link_js_package.bzl", link_11 = "link_js_package")

# buildifier: disable=unnamed-macro
def link_js_packages():
    "Generated list of link_js_package() target generators and first party linked packages corresponding to the packages in @//:pnpm-lock.yaml"
    root_path = ""
    importer_paths = ["."]
    is_root = native.package_name() == root_path
    is_direct = False
    for import_path in importer_paths:
        importer_package_path = _paths.normalize(_paths.join(root_path, import_path))
        if importer_package_path == ".":
            importer_package_path = ""
        if importer_package_path == native.package_name():
            is_direct = True
    if not is_root and not is_direct:
        msg = "The link_js_packages() macro loaded from @npm//:defs.bzl and called in bazel package '%s' may only be called in the bazel package(s) corresponding to the root package '' and packages corresponding to importer paths ['.']" % native.package_name()
        fail(msg)

    link_0(False)
    link_1(False)
    link_2(False)
    link_3(False)
    link_4(False)
    link_5(False)
    link_6(False)
    link_7(False)
    link_8(False)
    link_9(False)
    link_10(False)
    link_11(False)

def package(name, import_path = "."):
    package_path = _paths.normalize(_paths.join("", import_path))
    if package_path == ".":
        package_path = ""
    return Label("@//{package_path}:jsp__{bazel_name}".format(
        package_path = package_path,
        bazel_name = _pnpm_utils.bazel_name(name),
    ))

def package_dir(name, import_path = "."):
    package_path = _paths.normalize(_paths.join("", import_path))
    if package_path == ".":
        package_path = ""
    return Label("@//{package_path}:jsp__{bazel_name}__dir".format(
        package_path = package_path,
        bazel_name = _pnpm_utils.bazel_name(name),
    ))
