# Override http_archive for local testing
local_repository(
    name = "aspect_rules_terser",
    path = "../..",
)

#---SNIP--- Below here is re-used in the workspace snippet published on releases

######################
# rules_terser setup #
######################

# Fetch the Bazel module dependencies

load("@aspect_rules_terser//terser:dependencies.bzl", "rules_terser_dependencies")

rules_terser_dependencies()

# Fetch and register a nodejs interpreter, if you haven't already

load("@rules_nodejs//nodejs:repositories.bzl", "DEFAULT_NODE_VERSION", "nodejs_register_toolchains")

nodejs_register_toolchains(
    name = "node",
    node_version = DEFAULT_NODE_VERSION,
)

# Fetch and register the terser tool
load("@aspect_rules_terser//terser:repositories.bzl", "terser_repositories")

terser_repositories(name = "terser")

load("@terser//:npm_repositories.bzl", terser_npm_repositories = "npm_repositories")

terser_npm_repositories()
