"@generated by @aspect_rules_js//js/private:translate_pnpm_lock.bzl from pnpm lock file @//:pnpm-lock.yaml"

load("@npm__at_jridgewell_gen-mapping__0.3.1__links//:defs.bzl", link_0 = "link_js_package")
load("@npm__at_jridgewell_resolve-uri__3.0.7__links//:defs.bzl", link_1 = "link_js_package")
load("@npm__at_jridgewell_set-array__1.1.1__links//:defs.bzl", link_2 = "link_js_package")
load("@npm__at_jridgewell_source-map__0.3.2__links//:defs.bzl", link_3 = "link_js_package")
load("@npm__at_jridgewell_sourcemap-codec__1.4.13__links//:defs.bzl", link_4 = "link_js_package")
load("@npm__at_jridgewell_trace-mapping__0.3.13__links//:defs.bzl", link_5 = "link_js_package")
load("@npm__acorn__8.7.1__links//:defs.bzl", link_6 = "link_js_package")
load("@npm__buffer-from__1.1.2__links//:defs.bzl", link_7 = "link_js_package")
load("@npm__commander__2.20.3__links//:defs.bzl", link_8 = "link_js_package")
load("@npm__source-map-support__0.5.21__links//:defs.bzl", link_9 = "link_js_package")
load("@npm__source-map__0.6.1__links//:defs.bzl", link_10 = "link_js_package")
load("@npm__terser__5.14.0__links//:defs.bzl", link_11 = "link_js_package")

# buildifier: disable=unnamed-macro
def link_js_packages():
    "Generated list of link_js_package() target generators and first-party linked packages corresponding to the packages in @//:pnpm-lock.yaml"
    root_package = ""
    link_packages = [""]
    is_root = native.package_name() == root_package
    is_direct = False
    for link_package in link_packages:
        if link_package == native.package_name():
            is_direct = True
    if not is_root and not is_direct:
        msg = "The link_js_packages() macro loaded from @npm//:defs.bzl and called in bazel package '%s' may only be called in the bazel package(s) corresponding to the root package '' and packages ['']" % native.package_name()
        fail(msg)

    link_0(name = "direct_link__at_jridgewell_gen-mapping", direct = None, fail_if_no_link = False)
    link_1(name = "direct_link__at_jridgewell_resolve-uri", direct = None, fail_if_no_link = False)
    link_2(name = "direct_link__at_jridgewell_set-array", direct = None, fail_if_no_link = False)
    link_3(name = "direct_link__at_jridgewell_source-map", direct = None, fail_if_no_link = False)
    link_4(name = "direct_link__at_jridgewell_sourcemap-codec", direct = None, fail_if_no_link = False)
    link_5(name = "direct_link__at_jridgewell_trace-mapping", direct = None, fail_if_no_link = False)
    link_6(name = "direct_link__acorn", direct = None, fail_if_no_link = False)
    link_7(name = "direct_link__buffer-from", direct = None, fail_if_no_link = False)
    link_8(name = "direct_link__commander", direct = None, fail_if_no_link = False)
    link_9(name = "direct_link__source-map-support", direct = None, fail_if_no_link = False)
    link_10(name = "direct_link__source-map", direct = None, fail_if_no_link = False)
    link_11(name = "direct_link__terser", direct = None, fail_if_no_link = False)
