"@generated by @aspect_rules_js//npm/private:npm_translate_lock.bzl from pnpm lock file @//:pnpm-lock.yaml"

load("@aspect_rules_js//npm:npm_import.bzl", "npm_import")

def npm_repositories():
    "Generated npm_import repository rules corresponding to npm packages in @//:pnpm-lock.yaml"
    npm_import(
        name = "npm__at_jridgewell_gen-mapping__0.3.2",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "@jridgewell/gen-mapping",
        version = "0.3.2",
        integrity = "sha512-mh65xKQAzI6iBcFzwv28KVWSmCkdRBWoOh+bYQGW3+6OZvbbN3TqMGo5hqYxQniRcH9F2VZIoJCm4pa3BPDK/A==",
        deps = {
            "@jridgewell/set-array": "1.1.2",
            "@jridgewell/sourcemap-codec": "1.4.14",
            "@jridgewell/trace-mapping": "0.3.14",
        },
        transitive_closure = {
            "@jridgewell/gen-mapping": ["0.3.2"],
            "@jridgewell/set-array": ["1.1.2"],
            "@jridgewell/sourcemap-codec": ["1.4.14"],
            "@jridgewell/trace-mapping": ["0.3.14"],
            "@jridgewell/resolve-uri": ["3.1.0"],
        },
    )

    npm_import(
        name = "npm__at_jridgewell_resolve-uri__3.1.0",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "@jridgewell/resolve-uri",
        version = "3.1.0",
        integrity = "sha512-F2msla3tad+Mfht5cJq7LSXcdudKTWCVYUgw6pLFOOHSTtZlj6SWNYAp+AhuqLmWdBO2X5hPrLcu8cVP8fy28w==",
        transitive_closure = {
            "@jridgewell/resolve-uri": ["3.1.0"],
        },
    )

    npm_import(
        name = "npm__at_jridgewell_set-array__1.1.2",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "@jridgewell/set-array",
        version = "1.1.2",
        integrity = "sha512-xnkseuNADM0gt2bs+BvhO0p78Mk762YnZdsuzFV018NoG1Sj1SCQvpSqa7XUaTam5vAGasABV9qXASMKnFMwMw==",
        transitive_closure = {
            "@jridgewell/set-array": ["1.1.2"],
        },
    )

    npm_import(
        name = "npm__at_jridgewell_source-map__0.3.2",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "@jridgewell/source-map",
        version = "0.3.2",
        integrity = "sha512-m7O9o2uR8k2ObDysZYzdfhb08VuEml5oWGiosa1VdaPZ/A6QyPkAJuwN0Q1lhULOf6B7MtQmHENS743hWtCrgw==",
        deps = {
            "@jridgewell/gen-mapping": "0.3.2",
            "@jridgewell/trace-mapping": "0.3.14",
        },
        transitive_closure = {
            "@jridgewell/source-map": ["0.3.2"],
            "@jridgewell/gen-mapping": ["0.3.2"],
            "@jridgewell/trace-mapping": ["0.3.14"],
            "@jridgewell/resolve-uri": ["3.1.0"],
            "@jridgewell/sourcemap-codec": ["1.4.14"],
            "@jridgewell/set-array": ["1.1.2"],
        },
    )

    npm_import(
        name = "npm__at_jridgewell_sourcemap-codec__1.4.14",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "@jridgewell/sourcemap-codec",
        version = "1.4.14",
        integrity = "sha512-XPSJHWmi394fuUuzDnGz1wiKqWfo1yXecHQMRf2l6hztTO+nPru658AyDngaBe7isIxEkRsPR3FZh+s7iVa4Uw==",
        transitive_closure = {
            "@jridgewell/sourcemap-codec": ["1.4.14"],
        },
    )

    npm_import(
        name = "npm__at_jridgewell_trace-mapping__0.3.14",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "@jridgewell/trace-mapping",
        version = "0.3.14",
        integrity = "sha512-bJWEfQ9lPTvm3SneWwRFVLzrh6nhjwqw7TUFFBEMzwvg7t7PCDenf2lDwqo4NQXzdpgBXyFgDWnQA+2vkruksQ==",
        deps = {
            "@jridgewell/resolve-uri": "3.1.0",
            "@jridgewell/sourcemap-codec": "1.4.14",
        },
        transitive_closure = {
            "@jridgewell/trace-mapping": ["0.3.14"],
            "@jridgewell/resolve-uri": ["3.1.0"],
            "@jridgewell/sourcemap-codec": ["1.4.14"],
        },
    )

    npm_import(
        name = "npm__acorn__8.8.0",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "acorn",
        version = "8.8.0",
        integrity = "sha512-QOxyigPVrpZ2GXT+PFyZTl6TtOFc5egxHIP9IlQ+RbupQuX4RkT/Bee4/kQuC02Xkzg84JcT7oLYtDIQxp+v7w==",
        transitive_closure = {
            "acorn": ["8.8.0"],
        },
    )

    npm_import(
        name = "npm__buffer-from__1.1.2",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "buffer-from",
        version = "1.1.2",
        integrity = "sha512-E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==",
        transitive_closure = {
            "buffer-from": ["1.1.2"],
        },
    )

    npm_import(
        name = "npm__commander__2.20.3",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "commander",
        version = "2.20.3",
        integrity = "sha512-GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==",
        transitive_closure = {
            "commander": ["2.20.3"],
        },
    )

    npm_import(
        name = "npm__source-map-support__0.5.21",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "source-map-support",
        version = "0.5.21",
        integrity = "sha512-uBHU3L3czsIyYXKX88fdrGovxdSCoTGDRZ6SYXtSRxLZUzHg5P/66Ht6uoUlHu9EZod+inXhKo3qQgwXUT/y1w==",
        deps = {
            "buffer-from": "1.1.2",
            "source-map": "0.6.1",
        },
        transitive_closure = {
            "source-map-support": ["0.5.21"],
            "buffer-from": ["1.1.2"],
            "source-map": ["0.6.1"],
        },
    )

    npm_import(
        name = "npm__source-map__0.6.1",
        root_package = "",
        link_workspace = "",
        link_packages = {},
        package = "source-map",
        version = "0.6.1",
        integrity = "sha512-UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==",
        transitive_closure = {
            "source-map": ["0.6.1"],
        },
    )

    npm_import(
        name = "npm__terser__5.14.0",
        root_package = "",
        link_workspace = "",
        link_packages = {
            "": ["terser"],
        },
        package = "terser",
        version = "5.14.0",
        integrity = "sha512-JC6qfIEkPBd9j1SMO3Pfn+A6w2kQV54tv+ABQLgZr7dA3k/DL/OBoYSWxzVpZev3J+bUHXfr55L8Mox7AaNo6g==",
        deps = {
            "@jridgewell/source-map": "0.3.2",
            "acorn": "8.8.0",
            "commander": "2.20.3",
            "source-map-support": "0.5.21",
        },
        transitive_closure = {
            "terser": ["5.14.0"],
            "@jridgewell/source-map": ["0.3.2"],
            "acorn": ["8.8.0"],
            "commander": ["2.20.3"],
            "source-map-support": ["0.5.21"],
            "buffer-from": ["1.1.2"],
            "source-map": ["0.6.1"],
            "@jridgewell/gen-mapping": ["0.3.2"],
            "@jridgewell/trace-mapping": ["0.3.14"],
            "@jridgewell/resolve-uri": ["3.1.0"],
            "@jridgewell/sourcemap-codec": ["1.4.14"],
            "@jridgewell/set-array": ["1.1.2"],
        },
    )
