"@generated by @aspect_rules_js//npm/private:translate_pnpm_lock.bzl from pnpm lock file @//:pnpm-lock.yaml"

load("@aspect_rules_js//npm:npm_import.bzl", "npm_import")

def npm_repositories():
    "Generated npm_import repository rules corresponding to npm packages in @//:pnpm-lock.yaml"
    npm_import(
        name = "npm__at_jridgewell_gen-mapping__0.3.1",
        integrity = "sha512-GcHwniMlA2z+WFPWuY8lp3fsza0I8xPFMWL5+n8LYyP6PSvPrXf4+n8stDHZY2DM0zy9sVkRDy1jDI4XGzYVqg==",
        root_package = "",
        link_workspace = "",
        link_packages = [],
        package = "@jridgewell/gen-mapping",
        version = "0.3.1",
        deps = {
            "@jridgewell/set-array": "1.1.1",
            "@jridgewell/sourcemap-codec": "1.4.13",
            "@jridgewell/trace-mapping": "0.3.13",
        },
        transitive_closure = {
            "@jridgewell/gen-mapping": ["0.3.1"],
            "@jridgewell/set-array": ["1.1.1"],
            "@jridgewell/sourcemap-codec": ["1.4.13"],
            "@jridgewell/trace-mapping": ["0.3.13"],
            "@jridgewell/resolve-uri": ["3.0.7"],
        },
    )

    npm_import(
        name = "npm__at_jridgewell_resolve-uri__3.0.7",
        integrity = "sha512-8cXDaBBHOr2pQ7j77Y6Vp5VDT2sIqWyWQ56TjEq4ih/a4iST3dItRe8Q9fp0rrIl9DoKhWQtUQz/YpOxLkXbNA==",
        root_package = "",
        link_workspace = "",
        link_packages = [],
        package = "@jridgewell/resolve-uri",
        version = "3.0.7",
        transitive_closure = {
            "@jridgewell/resolve-uri": ["3.0.7"],
        },
    )

    npm_import(
        name = "npm__at_jridgewell_set-array__1.1.1",
        integrity = "sha512-Ct5MqZkLGEXTVmQYbGtx9SVqD2fqwvdubdps5D3djjAkgkKwT918VNOz65pEHFaYTeWcukmJmH5SwsA9Tn2ObQ==",
        root_package = "",
        link_workspace = "",
        link_packages = [],
        package = "@jridgewell/set-array",
        version = "1.1.1",
        transitive_closure = {
            "@jridgewell/set-array": ["1.1.1"],
        },
    )

    npm_import(
        name = "npm__at_jridgewell_source-map__0.3.2",
        integrity = "sha512-m7O9o2uR8k2ObDysZYzdfhb08VuEml5oWGiosa1VdaPZ/A6QyPkAJuwN0Q1lhULOf6B7MtQmHENS743hWtCrgw==",
        root_package = "",
        link_workspace = "",
        link_packages = [],
        package = "@jridgewell/source-map",
        version = "0.3.2",
        deps = {
            "@jridgewell/gen-mapping": "0.3.1",
            "@jridgewell/trace-mapping": "0.3.13",
        },
        transitive_closure = {
            "@jridgewell/source-map": ["0.3.2"],
            "@jridgewell/gen-mapping": ["0.3.1"],
            "@jridgewell/trace-mapping": ["0.3.13"],
            "@jridgewell/resolve-uri": ["3.0.7"],
            "@jridgewell/sourcemap-codec": ["1.4.13"],
            "@jridgewell/set-array": ["1.1.1"],
        },
    )

    npm_import(
        name = "npm__at_jridgewell_sourcemap-codec__1.4.13",
        integrity = "sha512-GryiOJmNcWbovBxTfZSF71V/mXbgcV3MewDe3kIMCLyIh5e7SKAeUZs+rMnJ8jkMolZ/4/VsdBmMrw3l+VdZ3w==",
        root_package = "",
        link_workspace = "",
        link_packages = [],
        package = "@jridgewell/sourcemap-codec",
        version = "1.4.13",
        transitive_closure = {
            "@jridgewell/sourcemap-codec": ["1.4.13"],
        },
    )

    npm_import(
        name = "npm__at_jridgewell_trace-mapping__0.3.13",
        integrity = "sha512-o1xbKhp9qnIAoHJSWd6KlCZfqslL4valSF81H8ImioOAxluWYWOpWkpyktY2vnt4tbrX9XYaxovq6cgowaJp2w==",
        root_package = "",
        link_workspace = "",
        link_packages = [],
        package = "@jridgewell/trace-mapping",
        version = "0.3.13",
        deps = {
            "@jridgewell/resolve-uri": "3.0.7",
            "@jridgewell/sourcemap-codec": "1.4.13",
        },
        transitive_closure = {
            "@jridgewell/trace-mapping": ["0.3.13"],
            "@jridgewell/resolve-uri": ["3.0.7"],
            "@jridgewell/sourcemap-codec": ["1.4.13"],
        },
    )

    npm_import(
        name = "npm__acorn__8.7.1",
        integrity = "sha512-Xx54uLJQZ19lKygFXOWsscKUbsBZW0CPykPhVQdhIeIwrbPmJzqeASDInc8nKBnp/JT6igTs82qPXz069H8I/A==",
        root_package = "",
        link_workspace = "",
        link_packages = [],
        package = "acorn",
        version = "8.7.1",
        transitive_closure = {
            "acorn": ["8.7.1"],
        },
    )

    npm_import(
        name = "npm__buffer-from__1.1.2",
        integrity = "sha512-E+XQCRwSbaaiChtv6k6Dwgc+bx+Bs6vuKJHHl5kox/BaKbhiXzqQOwK4cO22yElGp2OCmjwVhT3HmxgyPGnJfQ==",
        root_package = "",
        link_workspace = "",
        link_packages = [],
        package = "buffer-from",
        version = "1.1.2",
        transitive_closure = {
            "buffer-from": ["1.1.2"],
        },
    )

    npm_import(
        name = "npm__commander__2.20.3",
        integrity = "sha512-GpVkmM8vF2vQUkj2LvZmD35JxeJOLCwJ9cUkugyk2nuhbv3+mJvpLYYt+0+USMxE+oj+ey/lJEnhZw75x/OMcQ==",
        root_package = "",
        link_workspace = "",
        link_packages = [],
        package = "commander",
        version = "2.20.3",
        transitive_closure = {
            "commander": ["2.20.3"],
        },
    )

    npm_import(
        name = "npm__source-map-support__0.5.21",
        integrity = "sha512-uBHU3L3czsIyYXKX88fdrGovxdSCoTGDRZ6SYXtSRxLZUzHg5P/66Ht6uoUlHu9EZod+inXhKo3qQgwXUT/y1w==",
        root_package = "",
        link_workspace = "",
        link_packages = [],
        package = "source-map-support",
        version = "0.5.21",
        deps = {
            "buffer-from": "1.1.2",
            "source-map": "0.6.1",
        },
        transitive_closure = {
            "source-map-support": ["0.5.21"],
            "buffer-from": ["1.1.2"],
            "source-map": ["0.6.1"],
        },
    )

    npm_import(
        name = "npm__source-map__0.6.1",
        integrity = "sha512-UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==",
        root_package = "",
        link_workspace = "",
        link_packages = [],
        package = "source-map",
        version = "0.6.1",
        transitive_closure = {
            "source-map": ["0.6.1"],
        },
    )

    npm_import(
        name = "npm__terser__5.14.0",
        integrity = "sha512-JC6qfIEkPBd9j1SMO3Pfn+A6w2kQV54tv+ABQLgZr7dA3k/DL/OBoYSWxzVpZev3J+bUHXfr55L8Mox7AaNo6g==",
        root_package = "",
        link_workspace = "",
        link_packages = [""],
        package = "terser",
        version = "5.14.0",
        deps = {
            "@jridgewell/source-map": "0.3.2",
            "acorn": "8.7.1",
            "commander": "2.20.3",
            "source-map-support": "0.5.21",
        },
        transitive_closure = {
            "terser": ["5.14.0"],
            "@jridgewell/source-map": ["0.3.2"],
            "acorn": ["8.7.1"],
            "commander": ["2.20.3"],
            "source-map-support": ["0.5.21"],
            "buffer-from": ["1.1.2"],
            "source-map": ["0.6.1"],
            "@jridgewell/gen-mapping": ["0.3.1"],
            "@jridgewell/trace-mapping": ["0.3.13"],
            "@jridgewell/resolve-uri": ["3.0.7"],
            "@jridgewell/sourcemap-codec": ["1.4.13"],
            "@jridgewell/set-array": ["1.1.1"],
        },
    )
