name: CI - Aspect Workflows
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
permissions:
  id-token: write
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  # Indicates where the aspect CLI should look for .aspect/config.json
  ASPECT_WORKSPACE: ${{ github.workspace }}
  # Skip the --remote flag on fork PRs, which do not have access to secrets
  REMOTE_FLAG: ${{ secrets.ASPECT_OSS_API_TOKEN != '' && '--remote' || '' }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: aspect-build/setup-aspect@b1e9d142e86f63c10d603304daa22bf80492e24c # v2026.25.1
        with:
          aspect-api-token: ${{ secrets.ASPECT_OSS_API_TOKEN }}
      - name: Test
        run: aspect test $REMOTE_FLAG --task:name=test -- //...
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: aspect-build/setup-aspect@b1e9d142e86f63c10d603304daa22bf80492e24c # v2026.25.1
        with:
          aspect-api-token: ${{ secrets.ASPECT_OSS_API_TOKEN }}
      - name: Format
        run: aspect format $REMOTE_FLAG --task:name=format
  buildifier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: aspect-build/setup-aspect@b1e9d142e86f63c10d603304daa22bf80492e24c # v2026.25.1
        with:
          aspect-api-token: ${{ secrets.ASPECT_OSS_API_TOKEN }}
      - name: Buildifier
        run: aspect buildifier $REMOTE_FLAG --task:name=buildifier
  test-e2e-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: aspect-build/setup-aspect@b1e9d142e86f63c10d603304daa22bf80492e24c # v2026.25.1
        with:
          aspect-api-token: ${{ secrets.ASPECT_OSS_API_TOKEN }}
      - name: Test (e2e/smoke)
        working-directory: e2e/smoke
        run: aspect test $REMOTE_FLAG --task:name=test-e2e-smoke -- //...
  gazelle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: aspect-build/setup-aspect@b1e9d142e86f63c10d603304daa22bf80492e24c # v2026.25.1
        with:
          aspect-api-token: ${{ secrets.ASPECT_OSS_API_TOKEN }}
      - name: Gazelle
        run: aspect gazelle $REMOTE_FLAG --task:name=gazelle
